### PR TITLE
PyPI package pulls

### PR DESCRIPTION
**Pull request by jeffsmohan**
Remaining Issues:
- When creating new packages from PyPI data, do we leave category blank? Is there any good way to fill that in?
- I didn't add any settings for whether the site is Django or Python Packages; I'll leave it up to you how you want to do that. All I added was a couple management commands for "update everything from PyPI," which is suitable for a cron job or whatever. 
- Should be turned into tasks ASAP. To taskify the code once celery is up and running, you should turn update_outdated_packages into a periodic task (running every 10 minutes, every hour, whatever) and it should be spawning separate update_or_create_package tasks (instead of doing them as function calls, as it does now).
- The two main handler functions would benefit hugely from some logging, but since they're run both from the web as well as cron/tasks I couldn't just throw prints in there. Once you have your logging infrastructure, let me know and I can add some logs.

### CODE REVIEW

**Comment by pydanny** [comment]
Absolutely brillant work. This will serve as an excellent foundation for us going forward. The core of this will be driving out PyPI integration on Packaginator.

However, because some stuff we've introduced and will introduce with packaginator conflicts with part of this pull request, even with heavy edits I may not be able to directly accept this pull request. What I will be doing is integrating large - nay giant portions of this into Packaginator and I'll make sure you are fully credited for your hard work.

**Comment by pydanny** [comment]
Would you be up to hacking on this PyPI stuff this weekend? We could sit together and just get it done in a trivial amount of time and make it work in Packaginator.

**Comment by jeffsmohan** [comment]
No worries! I can't imagine trying to organize and merge 15 people
working at the same time on such a small codebase. The good news is
that most of the pypi app you should be able to pluck and out throw
back in without a lot of changes. Then you just have to worry about
how it's talking to the package model, which presumably is the model
that's changing out from under our feet.

Anyway, me and my friend are supposed to be working hard-core this
whole weekend on our side project. But I can probably spare a half day
or so to knock this stuff out with you. When were you thinking?

jeff

On Tue, Mar 15, 2011 at 10:15 AM, pydanny
reply@reply.github.com
wrote:

**Comment by pydanny** [comment]
Jeff - I'm throwing a couple guys at this here at the sprint. They are looking at your work and will be bringing parts of it in.

**Comment by jeffsmohan** [comment]
Cool. Consider it entirely bequeathed to your care. You and your
fellow sprinters are free to use it or not however you see fit. And if
you decide you'd like me to work on it a bit more after the sprints,
let me know!

On Wed, Mar 16, 2011 at 3:38 PM, pydanny
reply@reply.github.com
wrote:

**Pull request closed without merging**
